version: '3.5'
services:
  nginx-loadbalancer:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    network_mode: bridge
    
volumes:
  nginx: